[build]
  publish = "."
  command = "true"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "netlify-plugin-checklinks"

  [plugins.inputs]
    skipPatterns = [
      "https://fonts.gstatic.com",
      "https://fonts.googleapis.com",
      "https://www.linkedin.com",
      "https://www.flickr.com",
      "https://github.com"
    ]
